### ISSUE TITLE
Equal cells aren't equal after Cell.fromBoc

### ISSUE THREAD

**Issue by stspbu** [ton-community/ton#30]
I create some cells and want to compare them.
It works if we use constructors like this:

```
const cell = new Cell().withData("0101");
const cell2 = new Cell().withData("0101");
console.log(cell.equals(cell2)); // true
```

But it doesn't work if we use `Cell.fromBoc`:
```
const cell = new Cell().withData("0101");
const cellboc = Cell.fromBoc(cell.toBoc())[0];
console.log(cell.equals(cellboc)); // false, but expected true
```

The problem is that the comparison fails on `bits.equals`, because `cellboc` has only 8 bits (`cellboc.bits.length`), while the first cell has 1023.

**Comment by ex3ndr** [comment]
Fixed in 12.2.8
