### ISSUE TITLE
Recovered Address

### ISSUE THREAD

**Issue by beltsys-labs** [ton-community/ton#34]
Hey guys!
Thank you for your great work!

 I'm new to ton.

I'm trying to retrieve the public address that personal sign, but I can't find any function or information in ton's sdk.
In ethereum it would be something like

              const msgHash = ethers.utils.hashMessage(msg);
              const msgHashBytes = ethers.utils.arrayify(msgHash);
              const recoveredPubKey = ethers.utils.recoverPublicKey(msgHashBytes, signature); 
              const recoveredAddress = ethers.utils.recoverAddress(msgHashBytes, signature);
              console.log("publickey",recoveredPubKey) 
              console.log("redover address", recoveredAddress)

What would be the equivalent in Ton?  or where I can get information, I have searched but I can't find anything about it
Regards

**Comment by ex3ndr** [comment]
It is impossible to do so, but you can try to call investigate what contract sent a message and if it is a wallet it have a get method to retrieve a public key
